# Generated by Django 3.2.2 on 2021-05-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_navbaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
