# Generated by Django 3.2.2 on 2021-05-22 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20210516_0158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=25)),
                ('child_folder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.folder')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Blog.folder'),
        ),
    ]
