# Generated by Django 3.2.2 on 2021-05-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_auto_20210522_0801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='child_folder',
        ),
        migrations.AddField(
            model_name='folder',
            name='child_folder',
            field=models.ManyToManyField(blank=True, null=True, related_name='_Blog_folder_child_folder_+', to='Blog.Folder'),
        ),
    ]
