# Generated by Django 3.2.2 on 2021-05-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_auto_20210522_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='child_folder',
            field=models.ManyToManyField(blank=True, related_name='_Blog_folder_child_folder_+', to='Blog.Folder'),
        ),
    ]
